# Generated by Django 4.2.3 on 2023-07-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("point_from_x", models.FloatField()),
                ("point_from_y", models.FloatField()),
                ("point_to_x", models.FloatField()),
                ("point_to_y", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "price",
            },
        ),
    ]
